name: greeting
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
    
jobs:
  job_greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1 
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} 
          issue-message: ‘#The first issue msg.' 
          pr-message: ‘The first pr msg.'
