
# action的名称
name: issue_close


# 触发条件,当issues被关闭时
on:
  issues:
    types:
      - closed


# 执行的任务，共两个
jobs:

  # 任务一： 给该issue打上一个标签
  job1_label_issues:
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
      - uses: actions/github-script@v6  # 用到一个第三方编写的actions
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["closed"]
            })

  # 任务二：给该issue添加一条注释
  job_2_add_comment:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue has been closed.
